[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; decodes a PANIC backtrace into file/line automatically
monitor_filters = esp32_exception_decoder, time
board_build.partitions = huge_app.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    olikraus/U8g2 @ ^2.35.19
    adafruit/RTClib @ ^2.1.4
    h2zero/NimBLE-Arduino @ ^1.4.1
